#!/usr/bin/env bash
# Configures an Ubuntu server: localhost=127.0.0.2, facebook.com=8.8.8.8

cp /etc/hosts /tmp/hosts.tmp
sed 's/127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /tmp/hosts.tmp > /tmp/hosts.new

if grep -q "facebook.com" /tmp/hosts.new; then
    sed 's/.*facebook\.com.*/8.8.8.8 facebook.com/' /tmp/hosts.new > /tmp/hosts.final
else
    echo "8.8.8.8 facebook.com" >> /tmp/hosts.new
    cp /tmp/hosts.new /tmp/hosts.final
fi

cp /tmp/hosts.final /etc/hosts
